### ISSUE TITLE
Build error when GO111MODULE=off

### ISSUE THREAD

**Issue by rhcarvalho** [getsentry/sentry-go#135]
- https://travis-ci.com/getsentry/sentry-go/builds/143482701
- https://travis-ci.com/getsentry/sentry-go/builds/143486213

Curiously, only happens with Go 1.13 and master (soon to be Go 1.14).
Explanation: we have a build flag requiring at least Go 1.13 to build the iris integration: https://github.com/getsentry/sentry-go/commit/8a225f85eab0a62ee9eace6568d618049311cfa8.

Looks like more people run into this problem with Iris recently -- https://github.com/kataras/iris/issues/1422

In our case here, I could not see a single reference to `github.com/kataras/iris`, it is always `github.com/kataras/iris/v12` -- however, as per Travis logs, `go get` seems to be trying to install `github.com/kataras/iris`

**Comment by rhcarvalho** [comment]
I found that `jet`, a dependency of `iris` merged a breaking change to their API 6 days ago in https://github.com/CloudyKit/jet/pull/112. This means that when GO111MODULE=off we pull the latest version of everything, and then `iris` and `jet` expect incompatible types, such that `go get` fails to build `iris`.

**Comment by tooolbox** [comment]
@rhcarvalho that change was reverted with https://github.com/CloudyKit/jet/pull/126, is that still an issue?

**Comment by rhcarvalho** [comment]
@tooolbox thank you for asking. I've re-run the Travis build https://travis-ci.com/getsentry/sentry-go/builds/143639883 and it is green :)

Thank you!!

---

Closing this issue for now, cutting another one to track the maintainability of integrations with external frameworks. With the introduction of Go Modules, there is less incentive to work with GO111MODULE=OFF, thus we may need some adjustments going forward to state what version combinations are supported and also improve the Travis config to prevent build failures in sentry-go in the same fashion as this case here (i.e., we should probably not try to support "go get all" without versions).
